name: rnaseq
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Core
  - python=3.10
  - r-base=4.3
  
  # Preprocessing & QC
  - fastqc=0.12.1
  - multiqc=1.19
  - trim-galore=0.6.10
  - cutadapt=4.6
  
  # Alignment & quantification
  - star=2.7.11a
  - samtools=1.19
  - subread=2.0.6
  
  # Utilities
  - sra-tools=3.0.10
  - parallel-fastq-dump=0.6.7
  - pigz=2.8
  
  # R packages
  - r-tidyverse=2.0.0
  - r-ggplot2=3.4.4
  - r-pheatmap=1.0.12
  - r-rcolorbrewer=1.1_3
  - r-ggrepel=0.9.5
  - bioconductor-deseq2=1.42.0
  - bioconductor-clusterprofiler=4.10.0
  - bioconductor-enhancedvolcano=1.20.0
  - bioconductor-org.mm.eg.db=3.18.0
  - bioconductor-annotationdbi=1.64.0
  - bioconductor-complexheatmap=2.18.0
